### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by sarahdesmarais** [sarahdesmarais/use-all-the-selectors#1]
@thomasjbradley

Line 33 - I am not sure how to target only the "strong botanical" to make it white
Line 53 - I am also not sure how to target specifically the .type list to make all the different zebra line backgrounds

Can you provide any clues? Am I close?
Thanks

**Comment by thomasjbradley** [comment]
Yep, here are some clues:

*Strong botanical—*
We’re looking for a selector that selects something when it is beside (after in the code) something else. See what element the `<strong>` comes after, and combine that with the "adjacent" selector.

*Zebra stripes—*
Check out the cheat sheet and look at all the `nth-*` classes:
https://learn-the-web.algonquindesign.ca/topics/css-selectors-units-cheat-sheet/#pseudo-classes
